### ISSUE TITLE
Allow slacktee to do /commands

### ISSUE THREAD

**Issue by treducks** [course-hero/slacktee#21]
Hi

Currently using slacktee to send notifications to administrators via various scripts but I would also like the ability to use /remind to setup reminders as well. Currently trying the following:

echo "/remind @user to do something in 10 minutes" | slacktee.sh -u @otheruser -p -m link_names

but it just prints that and /remind isn't invoked. Am I missing something? Is this even possible?

Thanks

Ben

**Comment by Chikashi-Kato** [comment]
Hi treducks, thank you for using slacktee! 
I tried to invoke slash commands through slacktee, but I couldn't find the way to make it work.
I'm assuming slash commands are not invoked in the messages posted through API. (I also tested [postMesage API](https://api.slack.com/methods/chat.postMessage), but it didn't work too).

I will try to research it more. If I find anything useful, I will let you know.

**Comment by Chikashi-Kato** [comment]
Unfortunately, slash commands are currently supported by only Slack applications, and we cannot invoke it through API. Please check [the reply from Slack](https://twitter.com/SlackAPI/status/662736738092126208).
Once it's supported by API, I will definitely add the function to slacktee.

**Comment by treducks** [comment]
Yeah, I saw the conversation on Twitter. Bummer but I'll live. Thanks for looking into it.

**Comment by Chikashi-Kato** [comment]
No problem! Thank you for using Slacktee! 
Please let me know if you have any enhancement ideas in future :)
