### ISSUE TITLE
Everything is posted as a quote...

### ISSUE THREAD

**Issue by scarolan** [course-hero/slacktee#23]
How do you get images to expand in the slack channel?  It's not as fun when you just see a url.

**Comment by Chikashi-Kato** [comment]
Could you try to use '-p' option?
Looks line Slack doesn't expand images in triple backticks.

This worked for me.
```
echo "https://imgs.xkcd.com/comics/regular_expressions.png" | ./slacktee.sh -p
```

**Comment by Chikashi-Kato** [comment]
Hi @scarolan, does '-p' work for you?

**Comment by Chikashi-Kato** [comment]
Since I didn't get reply from you for a while, I will close this issue.
Please feel free to let me know anytime, if '-p' option doesn't work for you.
