### ISSUE TITLE
slacktee.sh doesn't work with crontab because of $PATH issue...

### ISSUE THREAD

**Issue by piyushmandovra** [course-hero/slacktee#27]
slacktee.sh by default doesn't work with crontab because /usr/local/bin is not included in crontab path, so manually i have to move into /bin directory, it would be great if you move in /bin or /usr/bin directory by default.
I took quite long to figure out these thing.

**Comment by Chikashi-Kato** [comment]
I'm sorry for the late reply.
I got your point. You can change the target directly by specifying it as a parameter of `install.sh`, but doesn't it work for you? Here is the example: `bash ./slacktee/install.sh /usr/bin`

Please correct me if I'm wrong, but usually `/bin` is used for storing the commands which need to be available in single user mode, so I don't think it's a good idea to add it to there. ([This wikipedia page](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) is very helpful).
`/usr/bin` is probably fine, but personally, I would prefer to use it for storing the commands which are maintained by package managers. So, that is why I'm using `/usr/local/bin` as a default directly. 
Hopefully, this can convince you ;)

**Comment by Chikashi-Kato** [comment]
I will close this, but please feel free to let me know if you have any other ideas :)

**Comment by piyushmandovra** [comment]
I have only one idea to add, It will be good to add in readme that it won't work with crontab just because path issue, because I feel most people  gonna use it for scripting automation like me ;) and crontab is one of them, so adding in readme will be helpful.

**Comment by Chikashi-Kato** [comment]
Thank you so much for the suggestion! I will update README to add the note :)

**Comment by Chikashi-Kato** [comment]
Updated README!

**Comment by SurferL** [comment]
Just FYI to anyone who also hits this issue...

I initially installed Slacktee to `/usr/local/bin`, which also generated a `~/.slacktee`.

To get it working with crontab (as root), I had to install Slacktee to `/usr/bin`, and also move `~/.slacktee` to `/etc/slacktee.conf`
