### ISSUE TITLE
Fails silently if curl is not installed

### ISSUE THREAD

**Issue by mfabinski** [course-hero/slacktee#35]
Hello everybody,

I testet this script on a new server install where no curl was installed. The script failed silently which made it hard to find the cause of no message appearing in slack. (I know: rtfm, you stated it uses curl on README) 

Expected behaviour: check if curl command fails and output some kind of error message.

Otherwise it's a great project, with curl installed it works like a charm :+1:

**Comment by Chikashi-Kato** [comment]
Hello mfabinski, thank you for the feedback!
I'm glad to hear slacktee is working for you :)

I like the idea to check if 'curl' command is installed or not. 
I will implement the check at the beggining of the setup mode (`--setup`). Also, I will think the best way to fail gracefully while sending, and try to implement the logic.

**Comment by siosphere** [comment]
Fixed by #38

**Comment by Chikashi-Kato** [comment]
Merged #38!
