### ISSUE TITLE
Issues on Debian 8

### ISSUE THREAD

**Issue by wayneworkman** [course-hero/slacktee#37]
Hello,

I used to use slacktee on CentOS 7, worked great. I'm having issues getting it to work on Debian. I'm fairly certain I've copy/pasted the webhook url and token into the prompts correctly as before, I've typed in the correct channel as before, but something like `echo "testing 123" | slacktee.sh` isn't working for me, and there are no errors displayed.

the slacktee.sh command is available, and it's in my path:
```
root@FOGTESTING:~# command -v slacktee.sh
/usr/local/bin/slacktee.sh
root@FOGTESTING:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Where are the logs? What should I check?

Thanks,
Wayne

**Comment by wayneworkman** [comment]
Figured it out, had to install curl. Bare-minimum Debian 8 doesn't have curl installed.

**Comment by Chikashi-Kato** [comment]
Sorry for the delayed reply, wayneworkman. 
I'm glad you could find the root cause of the issue. 
Your PR #38 was awesome! I'm pretty sure, it can avoid same issue in future! ;)
