### ISSUE TITLE
No way to add new line to string passed?

### ISSUE THREAD

**Issue by CoreyJ87** [course-hero/slacktee#41]
I am probably just doing something wrong. But my string im sending to slack is one big string not multiple variables. So I'm trying to make new lines. \n does not work. How can make sure the new lines are parsed and not stripped?

**Comment by Chikashi-Kato** [comment]
As long as the input value contains a proper new line character, slacktee should handle it.
Could you post your test data here?

**Comment by CoreyJ87** [comment]
So this is the string im sending: 

slackString='\nOmbi' is running 'properly\nsonarr' is running 'properly\ncouchpo' is running 'properly\nglances' is running 'properly\nts3server' is running 'properly\nglances' is running properly

and here is how im sending it:
echo ${slackString} | slacktee.sh -p 

here is what I get back
\nOmbi is running properly\nsonarr is running properly\ncouchpo is running properly\nglances is running properly\nts3server is running properly\nglances is running properly

**Comment by Chikashi-Kato** [comment]
Sorry for the delayed reply, CoreyJ87.
Could you try to add `-e` option to `echo` command?

`echo -e ${slackString} | slacktee.sh -p`

It works on `bash` environment.

**Comment by CoreyJ87** [comment]
No problem on the delay. This is just for a fun project anyways. Thanks a
bunch man. That was it. I knew it was something small I was missing.

**Comment by Chikashi-Kato** [comment]
I'm glad the solution works for you! 
Thank you for using Slacktee :)
