### ISSUE TITLE
Messages are not dispatched from rsyslog

### ISSUE THREAD

**Issue by ky4k0b** [course-hero/slacktee#44]
in rsyslog.conf I have the following

`:msg, contains, "NODFLT001" ^/root/slacktee-master/slacktee.sh`

when the event with NODFLT appears nothing is sent to slack

**Comment by Chikashi-Kato** [comment]
Hi, thank you for using slacktee!
I'm not familiar with rsyslog but I'm assuming it is running as its own user on your system and slacktee couldn't find the configuration file correctly. 
Could you try to copy your .slacktee from your home directory to /etc and rename it to slacktee.conf? If you don't like to use host-wide configuration file, please try to copy .slacktee to rsyslog user's home directory.
If you don't like both of them, you can specify your configration file by using --config option (e.g. /root/slacktee-master/slacktee.sh --config /root/.slacktee)

**Comment by Chikashi-Kato** [comment]
I'm closing this issue, but please feel free to let me know if you have any other questions!

**Comment by ky4k0b** [comment]
Thanks! The trick worked.

**Comment by Chikashi-Kato** [comment]
Awesome! I'm glad to hear that, ky4k0b! Thank you for the update.
