### ISSUE TITLE
Copyright/Applying License

### ISSUE THREAD

**Issue by ikstream** [course-hero/slacktee#47]
Hi,

I really like slacktee and would like to use parts of it for a project. Therefore I have to change something.
As the Apache Licenses states, I have to mark my changes in the copyright notice.
Unfortunately there is none. 
There is a paragraph about applying the Apache license in its appendix, which states:

" APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format[...]" 

It would be great if you could add a copyright notice, so i can use your code, or do you prefer it in a different way?

Best regards

**Comment by Chikashi-Kato** [comment]
Hi ikstream, thank you for using slacktee.
I just added a copyright notice to `slacktee.sh`, but does it look good?

**Comment by ikstream** [comment]
Looks good, thank you very much
