### ISSUE TITLE
deb/rpm/whatever package?

### ISSUE THREAD

**Issue by pacak** [course-hero/slacktee#50]
A more standard way of distributing software in Linux OS is by using package manager - this allows to specify dependencies. There's at least two existing issues caused by the missing curl.

https://github.com/course-hero/slacktee/issues/35
https://github.com/course-hero/slacktee/issues/37

There is a workaround for this problem: https://github.com/course-hero/slacktee/pull/38/files but it will only check for curl when you try to use it for the first time, not when  trying to install it.

**Comment by Chikashi-Kato** [comment]
Hi pacak, thank you for your feedback. I agree that creating packages is great way to distribute slacktee. 
Unfortunately, I am not familiar with the process to create the packages. I will try to learn it, but it would be great if you can create it and contribute it to slacktee community!

**Comment by vaithak** [comment]
Is anyone working on this? If not then I would like to work on this issue.

**Comment by Chikashi-Kato** [comment]
Not yet! It would be really great if you can help us!

**Comment by vaithak** [comment]
Ok, I will start working on it.

**Comment by Chikashi-Kato** [comment]
Cool! Thanks!!

**Comment by vaithak** [comment]
Added the debian package. PR link: https://github.com/course-hero/slacktee/pull/51

**Comment by Chikashi-Kato** [comment]
Thank you for the PR! Let me review it. I will get back to you as soon as possible!

**Comment by Chikashi-Kato** [comment]
Found a RPM package created by Scott R. Shinn at Atomicorp. 
https://centos.pkgs.org/7/atomic-x86_64/slacktee-1.2.11-1.el7.art.x86_64.rpm.html

I am closing this issue, but I will continue to add more packages.

**Comment by Chikashi-Kato** [comment]
Scott R. Shinn at Atomicorp created a package for following distros!
- Centos 6/7
- RHEL 6/7
- Amazon Linux 1/2(LTS)
- Debian 8/9
- Ubuntu 14/16
Added the instruction to README
