### ISSUE TITLE
Tag people/channels

### ISSUE THREAD

**Issue by samskiter** [course-hero/slacktee#9]
Would it be possible to slack a message that uses e.g `@channel` or `@<username>` to notify people of things?

**Comment by Chikashi-Kato** [comment]
Now slacktee can notify people who is mentioned using `@` in the message.
To enable the notification, please use `link_names` or `full` mode of the message formatting option (`-m` | `--message-formatting`)!

**Comment by ky4k0b** [comment]
Hi Chikashi-Kato,

I'm kinda confused but is it possible to make my app that using slacktee to send direct messages to someone in my team?

**Comment by Chikashi-Kato** [comment]
Hi ky4k0b, 

Sorry for the delayed reply!
Yes, if you want to send a message to a user instead of channel, you can simply specify the user’s userid with -c option (e.g. slacktee.sh -c @chuck).
It’s usage example is also written in README, so please check it too!

Hope this helps!
